import { GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
// import { Inter } from 'next/font/google'
import styles from '../../styles/home.module.css'
import heroImg from '../../public/assets/hero.png'

import { db } from '../services/firebaseConnection'
import { collection, getDocs } from 'firebase/firestore'

// const inter = Inter({ subsets: ['latin'] })

interface HomeProps {
  posts: number;
  comments: number;
}

export default function Home( { posts, comments }: HomeProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tarefas Plus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.logoContent}>
          <Image 
            className={styles.hero}
            alt='Logo Tarefas+'
            src={heroImg}
            priority
          />
          <h1 className={styles.title}>Sistema feito para você organizar<br/>seus estudos e tarefas</h1>

          <div className={styles.infoContent}>
            <section className={styles.box}>
              <span>+{posts} postagens</span>
            </section>
            <section className={styles.box}>
              <span>+{comments} comentários</span>
            </section>
          </div>
        </div>
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps =async () => {
  
  // Buscar do banco o número de postagens e comentários para enviar ao componente
  const commentRef = collection(db, "comentarios")
  const commentSnapshot = await getDocs(commentRef)

  const postsRef = collection(db, "tarefas")
  const postsSnapshot = await getDocs(postsRef)

  return {
    props: {
      posts: postsSnapshot.size || 0,
      comments: commentSnapshot.size || 0
    },
    revalidate: 60  // Revalida as informações a cada 60 segundos e gera nova página0
  }
}